In [17]:
# Web-scraping code for the 2022-23 and 2023-24 March Madness tournaments
# Websites Used: NCAA Men's Basketball, College Basketball Sports Reference

In [18]:
# Kevin code
import pandas as pd

import requests
from bs4 import BeautifulSoup

# 2023 March Madness Match ups from the NCAA website
url22_23 = "https://www.ncaa.com/news/basketball-men/article/2023-04-18/2023-ncaa-bracket-scores-stats-march-madness-mens-tournament"

response = requests.get(url22_23)

soup = BeautifulSoup(response.text, parser="html.parser")

In [19]:
# Kevin code

# Searched for specific tag in the html of the wesbite
tournament_scores22_23 = soup.find_all("ul")[18].children

# Creating a data frame of the match ups that includes the two different teams and seeds, and the winner
marchMad22_23 = {"teamA":[], "teamB": [], "teamA Seed":[], "teamB Seed": [], "winner": []}

for pairing in tournament_scores22_23:
  if pairing == "\n":
    continue

  pairings = pairing.find("ul").children

  for pair in pairings:
    if pair == "\n":
      continue
    teams_info = pair.text.replace("\n","").split("| Watch the highlights")[:-1]

    for team in teams_info:

      teams = team.split("No.")[1:]

      infoA = teams[0].replace(",","").replace("(","").replace(")","").split()
      infoB = teams[1].replace(",","").replace("(","").replace(")","").split()

      nameA = " ".join(infoA[1 : -1])
      nameB = " ".join(infoB[1 : -1])

      seedA = int(infoA[0])
      seedB = int(infoB[0])

      scoreA = int(infoA[-1])
      scoreB = int(infoB[-1])

      marchMad22_23["teamA"].append(nameA)
      marchMad22_23["teamB"].append(nameB)
      marchMad22_23["teamA Seed"].append(seedA)
      marchMad22_23["teamB Seed"].append(seedB)
      if scoreA > scoreB:
        marchMad22_23["winner"].append(nameA)
      elif scoreB > scoreA:
        marchMad22_23["winner"].append(nameB)

In [20]:
# Kevin code
dfmarchMad22_23 = pd.DataFrame(marchMad22_23)
dfmarchMad22_23

             teamA            teamB  teamA Seed  teamB Seed          winner
0              FDU   Texas Southern          16          16             FDU
1      Arizona St.           Nevada          11          11     Arizona St.
2   Texas A&M - CC  SE Missouri St.          16          16  Texas A&M - CC
3       Pittsburgh  Mississippi St.          11          11      Pittsburgh
4          Houston   North Kentucky           1          16         Houston
..             ...              ...         ...         ...             ...
62             FAU       Kansas St.           9           3             FAU
63   San Diego St.        Creighton           5           6   San Diego St.
64   San Diego St.              FAU           5           9   San Diego St.
65           UConn         Miami FL           4           5           UConn
66           UConn    San Diego St.           4           5           UConn

[67 rows x 5 columns]

In [21]:
# Kevin code

# 2024 March Madness Match ups from the NCAA website
url23_24 = "https://www.ncaa.com/news/basketball-men/article/2024-12-06/2024-ncaa-bracket-scores-stats-march-madness-mens-tournament"

response = requests.get(url23_24)

soup = BeautifulSoup(response.text, parser="html.parser")

In [22]:
# Kevin Code
tournament_scores23_24 = soup.find_all("ul")[18].children

marchMad23_24 = {"teamA":[], "teamB": [], "teamA Seed":[], "teamB Seed": [], "winner": []}

for pairing in tournament_scores23_24:
  if pairing == "\n":
    continue

  pairings = pairing.find("ul").children

  for pair in pairings:
    if pair == "\n":
      continue
    teams_info = pair.text.replace("\n","").split("| Watch the highlights")[:-1]

    for team in teams_info:

      teams = team.split("No.")[1:]

      infoA = teams[0].replace(",","").replace("(","").replace(")","").replace("OT","").replace("2OT","").split()
      infoB = teams[1].replace(",","").replace("(","").replace(")","").replace("OT","").replace("2OT","").split()

      nameA = " ".join(infoA[1 : -1])
      nameB = " ".join(infoB[1 : -1])

      seedA = int(infoA[0])
      seedB = int(infoB[0])

      scoreA = int(infoA[-1])
      scoreB = int(infoB[-1])

      marchMad23_24["teamA"].append(nameA)
      marchMad23_24["teamB"].append(nameB)
      marchMad23_24["teamA Seed"].append(seedA)
      marchMad23_24["teamB Seed"].append(seedB)
      if scoreA > scoreB:
        marchMad23_24["winner"].append(nameA)
      elif scoreB > scoreA:
        marchMad23_24["winner"].append(nameB)

In [23]:
# Kevin code
dfmarchMad23_24 = pd.DataFrame(marchMad23_24)
dfmarchMad23_24

              teamA          teamB  teamA Seed  teamB Seed           winner
0            Wagner         Howard          16          16           Wagner
1    Colorado State       Virginia          10          10   Colorado State
2   Grambling State  Montana State          16          16  Grambling State
3          Colorado    Boise State          10          10         Colorado
4             UConn        Stetson           1          16            UConn
..              ...            ...         ...         ...              ...
62         NC State           Duke          11           4         NC State
63           Purdue      Tennessee           1           2           Purdue
64            UConn        Alabama           1           4            UConn
65           Purdue       NC State           1          11           Purdue
66            UConn         Purdue           1           1            UConn

[67 rows x 5 columns]

In [24]:
# Mack code

# web scraping the 22-23 team data for teams in March Madness that year
import time

url = "https://www.sports-reference.com/cbb/seasons/men/2023-school-stats.html"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# Find the specific table
table = soup.find("table", {"id": "basic_school_stats"})

thead_rows = table.find("thead").find_all("tr")
last_header_row = thead_rows[-1]
header_cells = last_header_row.find_all("th")
headers = [th.get_text(strip=True) for th in header_cells]

tbody_rows = table.find("tbody").find_all("tr")
data = []
for row in tbody_rows:
    cells = row.find_all(["th", "td"])
    row_data = []
    for cell in cells:
      text = cell.get_text(strip=True)
      row_data.append(text)
    data.append(row_data)
    time.sleep(0.1) # sleep timer to be respectful

df_2022 = pd.DataFrame(data, columns=headers)
df_march_2022 = df_2022[df_2022["School"].str.contains("NCAA")].copy()
df_march_2022["School"] = df_march_2022["School"].str.replace("NCAA", "")
df_march_2022.reset_index(drop=True, inplace=True)

In [25]:
# Mack code

# (Before I finished my webscrapping, my partner decided to manually get the seedings of each team himself)
# manually adds seeding for each team based on bracket seeding
team_seed_map = {
    "Alabama": 1,
    "Texas A&M-Corpus Christi": 16,
    "Maryland": 8,
    "West Virginia": 9,
    "San Diego State": 5,
    "College of Charleston": 12,
    "Virginia": 4,
    "Furman": 13,
    "Creighton": 6,
    "NC State": 11,
    "Baylor": 3,
    "UC Santa Barbara": 14,
    "Missouri": 7,
    "Utah State": 10,
    "Arizona": 2,
    "Princeton": 15,
    "Purdue": 1,
    "FDU": 16,
    "Memphis": 8,
    "Florida Atlantic": 9,
    "Duke": 5,
    "Oral Roberts": 12,
    "Tennessee": 4,
    "Louisiana": 13,
    "Kentucky": 6,
    "Providence": 11,
    "Kansas State": 3,
    "Montana State": 14,
    "Michigan State": 7,
    "Southern California": 10,
    "Marquette": 2,
    "Vermont": 15,
    "Southeast Missouri State": 16,
    "Texas Southern": 16,
    "Nevada": 11,
    "Mississippi State": 11,
    "Houston": 1,
    "Northern Kentucky": 16,
    "Iowa": 8,
    "Auburn": 9,
    "Miami (FL)": 5,
    "Drake": 12,
    "Indiana": 4,
    "Kent State": 13,
    "Iowa State": 6,
    "Pittsburgh": 11,
    "Xavier": 3,
    "Kennesaw State": 14,
    "Texas A&M": 7,
    "Penn State": 10,
    "Texas": 2,
    "Colgate": 15,
    "Kansas": 1,
    "Howard": 16,
    "Arkansas": 8,
    "Illinois": 9,
    "Saint Mary's (CA)": 5,
    "Virginia Commonwealth": 12,
    "Connecticut": 4,
    "Iona": 13,
    "TCU": 6,
    "Arizona State": 11,
    "Gonzaga": 3,
    "Grand Canyon": 14,
    "Northwestern": 7,
    "Boise State": 10,
    "UCLA": 2,
    "UNC Asheville": 15
}

# need this so i can rerun the code without it failing
if "Seed" in df_march_2022.columns:
    df_march_2022.drop(columns="Seed", inplace=True)

df_march_2022.insert(
    loc=df_march_2022.columns.get_loc("Rk") + 1,
    column="Seed",
    value=df_march_2022["School"].map(team_seed_map)
)

df_march_2022["Seed"] = df_march_2022["Seed"]

In [26]:
# Mack code

# cleaning the 2022 data to match the other dataset with matchups
for index in df_march_2022.index:
    if "State" in df_march_2022.loc[index, "School"]:
        df_march_2022.loc[index, "School"] = df_march_2022.loc[index, "School"].replace("State", "St.")

df_march_2022.loc[8, "School"] = df_march_2022.loc[8, "School"].replace("College", "Col")
df_march_2022.loc[14, "School"] = df_march_2022.loc[14, "School"].replace("Florida Atlantic", "FAU")
df_march_2022.loc[34, "School"] = "Miami FL"
df_march_2022.loc[39, "School"] = df_march_2022.loc[39, "School"].replace("St.", "State")
df_march_2022.loc[41, "School"] = df_march_2022.loc[41, "School"].replace("Northern", "North")
df_march_2022.loc[49, "School"] = "Saint Mary's"
df_march_2022.loc[51, "School"] = "SE Missouri St."
df_march_2022.loc[52, "School"] = "USC"
df_march_2022.loc[57, "School"] = "Texas A&M-CC"
df_march_2022.loc[59, "School"] = "UCSB"
df_march_2022.loc[65, "School"] = "VCU"
df_march_2022.loc[6, "School"] = "Boise St."
df_march_2022.loc[9, "School"] = "UConn"


# data preprocessing and formatting in preparation for combined dataset
dfmarchMad22_23 = dfmarchMad22_23.replace("Texas A&M - CC", "Texas A&M-CC")
dfmarchMad22_23 = dfmarchMad22_23.replace("Pitt", "Pittsburgh")

# weird apostrophe case
dfmarchMad22_23 = dfmarchMad22_23.replace("Saint Maryâ€™s", "Saint Mary's")

dfmarchMad22_23 = dfmarchMad22_23.replace("St. Maryâ€™s", "Saint Mary's")

# some columns leftover that are empty, dropping them
df_march_2022_final = df_march_2022.drop(columns=[""])

In [27]:
# Mack code

# code to combine 22-23 stats

import pandas as pd
import random
# use same randomized code every run
random.seed(42)

# Columns of interest (all numeric)
stats_columns = [
    'Seed', 'W-L%', 'SRS', 'SOS', 'Tm.', 'Opp.', 'MP', 'FG', 'FGA', 'FG%',
    '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'TRB', 'AST',
    'STL', 'BLK', 'TOV', 'PF'
]

# Convert these columns to numeric
df_march_2022_final[stats_columns] = df_march_2022_final[stats_columns].apply(
    pd.to_numeric, errors='coerce'
)

matchup_rows = []

# Loop through all matchups in your bracket DataFrame
for idx, row in dfmarchMad22_23.iterrows():
    team1 = row["teamA"]
    team2 = row["teamB"]
    winner = row["winner"]

    seed1 = row["teamA Seed"]
    seed2 = row["teamB Seed"]

    # Gather stats for both teams (assuming exact matching names)
    team1_stats = df_march_2022_final.loc[df_march_2022_final["School"] == team1].iloc[0]
    team2_stats = df_march_2022_final.loc[df_march_2022_final["School"] == team2].iloc[0]

    # Randomly decide which team goes first, since winning team is always first from the website
    if random.random() < 0.5:
        # keep the original order
        actualTeamA, actualTeamB = team1, team2
        actualSeedA, actualSeedB = seed1, seed2
        teamA_stats, teamB_stats = team1_stats, team2_stats
    else:
        # swap them
        actualTeamA, actualTeamB = team2, team1
        actualSeedA, actualSeedB = seed2, seed1
        teamA_stats, teamB_stats = team2_stats, team1_stats

    # Build a dictionary for each matchup
    matchup_dict = {
        "teamA": actualTeamA,
        "teamB": actualTeamB,
        "seedA": actualSeedA,
        "seedB": actualSeedB,
    }

    # Compute differences for each numeric column
    for col in stats_columns:
        matchup_dict[f"{col}_diff"] = teamA_stats[col] - teamB_stats[col]

    # Compute seed difference
    matchup_dict["seed_diff"] = actualSeedA - actualSeedB

    # Label: 1 if actualTeamA is the winner, 0 otherwise
    matchup_dict["winner"] = 1 if winner == actualTeamA else 0

    # Append to our matchup_rows list
    matchup_rows.append(matchup_dict)

# Convert the list of matchup dicts into a DataFrame
df_combined_22_23 = pd.DataFrame(matchup_rows)

df_combined_22_23

,teamA,teamB,seedA,seedB,Seed_diff,W-L%_diff,SRS_diff,SOS_diff,Tm._diff,Opp._diff,...,FT%_diff,ORB_diff,TRB_diff,AST_diff,STL_diff,BLK_diff,TOV_diff,PF_diff,seed_diff,winner
0,Texas Southern,FDU,16,16,0,-0.168,-1.58,4.78,-441,-226,...,-0.088,-22,42,-133,-60,42,86,-39,0,0
1,Arizona St.,Nevada,11,11,0,-0.028,1.28,1.77,162,209,...,-0.103,150,214,41,58,70,83,76,0,1
2,Texas A&M-CC,SE Missouri St.,16,16,0,0.158,4.83,-0.21,14,-173,...,0.083,78,44,39,45,-55,-23,-102,0,1
3,Pittsburgh,Mississippi St.,11,11,0,0.049,-0.84,-1.49,470,437,...,0.112,-76,13,24,-108,30,-34,68,0,1
4,North Kentucky,Houston,16,1,15,-0.263,-23.03,-7.68,-398,98,...,-0.037,-80,-305,-76,36,-93,25,-83,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Kansas St.,FAU,3,9,-6,-0.175,1.87,7.18,-293,-32,...,0.029,-70,-272,49,37,0,38,31,-6,0
63,Creighton,San Diego St.,6,5,1,-0.172,2.02,0.88,53,56,...,0.061,-120,-47,77,-77,1,-23,-148,1,0
64,FAU,San Diego St.,9,5,4,0.076,-1.89,-6.62,260,72,...,-0.003,-1,103,58,-10,-51,8,-21,4,0
65,Miami FL,UConn,5,4,1,-0.011,-8.97,-1.67,-139,160,...,0.023,-123,-249,-149,25,-75,-92,-165,1,0
66,UConn,San Diego St.,4,5,-1,-0.026,7.14,-0.41,289,26,...,0.039,81,118,180,-17,39,51,58,-1,1

In [28]:
# Mack code

# code to webscrape 23-24 stats for each team in march madness that year
import time

url = "https://www.sports-reference.com/cbb/seasons/men/2024-school-stats.html"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# Find the specific table
table = soup.find("table", {"id": "basic_school_stats"})

thead_rows = table.find("thead").find_all("tr")
last_header_row = thead_rows[-1]
header_cells = last_header_row.find_all("th")
headers = [th.get_text(strip=True) for th in header_cells]

tbody_rows = table.find("tbody").find_all("tr")
data = []
for row in tbody_rows:
    cells = row.find_all(["th", "td"])
    row_data = []
    for cell in cells:
      text = cell.get_text(strip=True)
      row_data.append(text)
    data.append(row_data)
    time.sleep(0.1) # sleep timer to be respectful

df_2023 = pd.DataFrame(data, columns=headers)

df_march_2023 = df_2023[df_2023["School"].str.contains("NCAA")].copy()
df_march_2023["School"] = df_march_2023["School"].str.replace("NCAA", "")
df_march_2023.reset_index(drop=True, inplace=True)

In [29]:
# cleaning the 2023 data to match the other dataset with matchups
for index in df_march_2023.index:
    if "St." in df_march_2023.loc[index, "School"]:
        df_march_2023.loc[index, "School"] = df_march_2023.loc[index, "School"].replace("St.", "State")

df_march_2023.loc[6, "School"] = "BYU"
df_march_2023.loc[9, "School"] = "Charleston"
df_march_2023.loc[19, "School"] = "Florida Atlantic"
df_march_2023.loc[33, "School"] = "McNeese"
df_march_2023.loc[38, "School"] = "NC State"
df_march_2023.loc[47, "School"] = "Saint Mary's"
df_march_2023.loc[12, "School"] = "UConn"
df_march_2023.loc[21, "School"] = "Grambling State"

dfmarchMad23_24 = dfmarchMad23_24.replace("Oregon 73", "Oregon")

In [30]:
# Mack code

# manually adds seeding for each team based on bracket seeding
team_seed_map = {
    "Akron": 14,
    "Alabama": 4,
    "Arizona": 2,
    "Auburn": 4,
    "Baylor": 3,
    "Boise State": 10,
    "BYU": 6,
    "Clemson": 6,
    "Colgate": 14,
    "Charleston": 13,
    "Colorado": 10,
    "Colorado State": 10,
    "UConn": 1,
    "Creighton": 3,
    "Dayton": 7,
    "Drake": 10,
    "Duke": 4,
    "Duquesne": 11,
    "Florida": 7,
    "Florida Atlantic": 8,
    "Gonzaga": 5,
    "Grambling State": 16,
    "Grand Canyon": 12,
    "Houston": 1,
    "Howard": 16,
    "Illinois": 3,
    "Iowa State": 2,
    "James Madison": 12,
    "Kansas": 4,
    "Kentucky": 3,
    "Long Beach State": 15,
    "Longwood": 16,
    "Marquette": 2,
    "McNeese": 12,
    "Michigan State": 9,
    "Mississippi State": 8,
    "Montana State": 16,
    "Morehead State": 14,
    "NC State": 11,
    "Nebraska": 8,
    "Nevada": 10,
    "New Mexico": 11,
    "North Carolina": 1,
    "Northwestern": 9,
    "Oakland": 14,
    "Oregon": 11,
    "Purdue": 1,
    "Saint Mary's": 5,
    "Saint Peter's": 15,
    "Samford": 13,
    "San Diego State": 5,
    "South Carolina": 6,
    "South Dakota State": 15,
    "Stetson": 16,
    "TCU": 9,
    "Tennessee": 2,
    "Texas": 7,
    "Texas A&M": 9,
    "Texas Tech": 1,
    "UAB": 1,
    "Utah State": 6,
    "Vermont": 13,
    "Virginia": 10,
    "Wagner": 16,
    "Washington State": 7,
    "Western Kentucky": 15,
    "Wisconsin": 5,
    "Yale": 13
}

# need this so i can rerun the code without it failing
if "Seed" in df_march_2023.columns:
    df_march_2023.drop(columns="Seed", inplace=True)

df_march_2023.insert(
    loc=df_march_2023.columns.get_loc("Rk") + 1,
    column="Seed",
    value=df_march_2023["School"].map(team_seed_map)
)

df_march_2023["Seed"] = df_march_2023["Seed"]

In [31]:
# Mack code

# code to combine 23-24 stats

random.seed(42)

# Columns of interest (all numeric)
stats_columns = ['Seed', 'W-L%', 'SRS', 'SOS', 'Tm.', 'Opp.', 'MP', 'FG', 'FGA', 'FG%',
    '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'TRB', 'AST',
    'STL', 'BLK', 'TOV', 'PF']

# Convert these columns to numeric
df_march_2023[stats_columns] = df_march_2023[stats_columns].apply(
    pd.to_numeric, errors='coerce'
)

matchup_rows = []

# Loop through all matchups in your bracket DataFrame
for idx, row in dfmarchMad23_24.iterrows():
    team1 = row["teamA"]
    team2 = row["teamB"]
    winner = row["winner"]

    seed1 = row["teamA Seed"]
    seed2 = row["teamB Seed"]

    # Gather stats for both teams (assuming exact matching names)
    team1_stats = df_march_2023.loc[df_march_2023["School"] == team1]
    team1_stats = team1_stats.iloc[0]

    team2_stats = df_march_2023.loc[df_march_2023["School"] == team2]
    team2_stats = team2_stats.iloc[0]

    # Randomly decide which team goes first
    if random.random() < 0.5:
        # keep the original order
        actualTeamA, actualTeamB = team1, team2
        actualSeedA, actualSeedB = seed1, seed2
        teamA_stats, teamB_stats = team1_stats, team2_stats
    else:
        # swap them
        actualTeamA, actualTeamB = team2, team1
        actualSeedA, actualSeedB = seed2, seed1
        teamA_stats, teamB_stats = team2_stats, team1_stats

    matchup_dict = {
        "teamA": actualTeamA,
        "teamB": actualTeamB,
        "seedA": actualSeedA,
        "seedB": actualSeedB,
    }

    for col in stats_columns:
        matchup_dict[f"{col}_diff"] = teamA_stats[col] - teamB_stats[col]

    matchup_dict["seed_diff"] = actualSeedA - actualSeedB

    # make winner label = None so model can predict
    matchup_dict["winner"] = 1 if winner == actualTeamA else 0

    matchup_rows.append(matchup_dict)

df_combined_23_24 = pd.DataFrame(matchup_rows)

df_combined_23_24

,teamA,teamB,seedA,seedB,Seed_diff,W-L%_diff,SRS_diff,SOS_diff,Tm._diff,Opp._diff,...,FT%_diff,ORB_diff,TRB_diff,AST_diff,STL_diff,BLK_diff,TOV_diff,PF_diff,seed_diff,winner
0,Howard,Wagner,16,16,0,-0.001,1.95,0.56,520,517,...,0.047,26,74,64,17,22,215,154,0,0
1,Colorado State,Virginia,10,10,0,0.018,2.95,-0.03,567,389,...,0.115,-15,96,139,-13,-56,102,153,0,1
2,Grambling State,Montana State,16,16,0,0.097,-4.29,-1.02,-199,-100,...,-0.020,109,90,-109,-23,31,65,-70,0,1
3,Colorado,Boise State,10,10,0,0.036,2.64,1.01,456,433,...,0.048,-16,136,196,32,2,101,-2,0,1
4,Stetson,UConn,16,1,15,-0.296,-31.79,-11.94,-569,30,...,0.023,-130,-337,-283,-59,-109,-14,-134,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Duke,NC State,4,11,-7,0.116,7.86,-0.57,-271,-555,...,-0.010,-32,-128,15,-62,-16,-43,-93,-7,0
63,Tennessee,Purdue,2,1,1,-0.122,-3.12,-1.18,-375,-265,...,0.031,-57,-184,-120,68,24,-75,93,1,0
64,Alabama,UConn,4,1,3,-0.249,-6.01,3.10,79,470,...,0.029,3,-86,-161,10,-55,55,84,3,0
65,NC State,Purdue,11,1,10,-0.238,-12.12,-2.67,-110,251,...,0.013,-61,-130,-184,85,6,-50,128,10,0
66,UConn,Purdue,1,1,0,0.053,1.77,-2.90,45,-155,...,0.023,-7,-24,28,34,75,-59,114,0,1

In [32]:
# Kevin code
df_combined_22_23.to_csv("MarchMadness2022-23.csv", index=False)
df_combined_23_24.to_csv("MarchMadness2023-24.csv", index=False)